# Form implementation generated from reading ui file '/Users/funway/project/python/TransferDog/ui/task_edit_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.labelTaskName = QtWidgets.QLabel(Dialog)
        self.labelTaskName.setGeometry(QtCore.QRect(60, 40, 71, 16))
        self.labelTaskName.setObjectName("labelTaskName")
        self.lineEditTaskName = QtWidgets.QLineEdit(Dialog)
        self.lineEditTaskName.setGeometry(QtCore.QRect(140, 40, 113, 21))
        self.lineEditTaskName.setObjectName("lineEditTaskName")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.labelTaskName.setText(_translate("Dialog", "TaskName"))
